# This file contains the source URL for the Flutter and Dart SDKs.
# By default, packages imported from source are resolved to their latest versions.
#
# For more information about Podfiles, see the offline documentation for CocoaPods
# (see the Getting Started guide for more information).
#

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

if ENV['FLUTTER_ROOT'].nil?
  raise "FLUTTER_ROOT not set. Please set FLUTTER_ROOT to the Flutter SDK root."
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_PHOTOS=1',
      ]
    end
  end
end

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join(
    File.dirname(__FILE__),
    'Flutter',
    'Generated.xcconfig'
  ), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

def load_from_environment
  @@flutter_root ||= flutter_root
end

class PodCommandError < StandardError
end

command = "platform :ios, '11.0'"

def flutter_ios_podfile_setup
  load_from_environment
end

platform :ios, '11.0'
flutter_ios_podfile_setup
